apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:       # Configure the pod
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0   # docker image
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password


---
# service configuration

apiVersion: v1
kind: Service
metadata:
  name: mongo-service   
spec:
  selector:             
    app: mongo
  ports:
    - protocol: TCP
      port: 27017          # Listener port
      targetPort: 27017  # forward port: the one mentioned in the deployment file for container